language: python

python:
  - "2.7"
  - "3.4"

services:
  - postgresql

# command to install requirements
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -r requirements-dev.txt --use-mirrors

# command to run tests, e.g. python setup.py test
script:
  - "py.test py.test --ds=mama_ng_control.testsettings mama_ng_control/apps/*/tests.py --cov=contentstore"
  - "flake8 ."
